--- !ditz.rubyforge.org,2008-03-06/issue 
title: handle multiple call/returns into the same function
desc: ""
type: :bugfix
component: CFGAnalysis
release: "0.2"
reporter: doebel <doebel@tudos.org>
status: :closed
disposition: :fixed
creation_time: 2012-08-16 14:42:00.787055 Z
references: []

id: bb66e390f5d52bf2061461b27e7e26e37f865eba
log_events: 
- - 2012-08-16 14:42:01.694920 Z
  - doebel <doebel@tudos.org>
  - created
  - ""
- - 2012-08-16 14:48:15.346949 Z
  - doebel <doebel@tudos.org>
  - changed status from unstarted to in_progress
  - ""
- - 2012-08-16 23:23:52.444221 Z
  - doebel <doebel@tudos.org>
  - commented
  - getting there. 1/2 test cases looks good, but needs validation. Test case 2 (twocalls) seems to be missing a final BB for the return from the second function call.
- - 2012-08-17 08:25:40.630575 Z
  - doebel <doebel@tudos.org>
  - closed with disposition fixed
  - ""
git_branch: 
